# Generated by Django 3.0.2 on 2020-01-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
